version: '3.8'

services:
  flask:
    build: ./api
    command: >
      sh -c "python3 app.py"
    volumes:
      - ./api:/app/api
    expose:
      - '5000'

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    expose:
      - '3000'
    command: ['npm', 'start']

  nginx:
    build: ./nginx
    ports:
      - '80:80' # Expose port 80 for HTTP traffic
    depends_on:
      - flask
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:
  media: {}
  nginx-certs: {}
